version: '3.1'

services:
    postgres:
      container_name: 'keycloak-postgres'
      image: postgres:13.1
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DATABASE: ${POSTGRES_USER}
        POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        pgdata: data-pstgresql
      ports:
      - '5432:5432'
      networks:
      - osdr-net-ext
      volumes:
      - data-pstgresql:/data

    keycloak:
        container_name: 'keycloak-server'
        image: leanda/keycloak:latest
        restart: always
        environment:
          DB_ADDR: postgres
          DB_USER: ${POSTGRES_USER}
          DB_PASSWORD: ${POSTGRES_PASSWORD}           
          DB_VENDOR: POSTGRES
          DB_DATABASE: ${POSTGRES_USER}
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          JDBC_PARAMS: 'connectTimeout=30'
        ports:
        - '18080:8080'
        - '18443:8443'
        volumes:
        - data-keycloak:/data
        networks:
        - osdr-net-ext
        depends_on:
        - postgres

volumes:
    data-keycloak:
    data-pstgresql:

networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
