version: '3.1'

services:
    postgres:
      container_name: 'keycloak-postgres'
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        POSTGRES_DATABASE: keycloak
        POSTGRES_ROOT_PASSWORD: keycloak
        pgdata: data-pstgresql
      ports:
      - '5432:5432'
      networks:
      - osdr-net-ext
      volumes:
      - data-pstgresql:/data

    keycloak:
        container_name: 'keycloak-server'
        image: leanda/keycloak:latest
        restart: always
        environment:
          DB_VENDOR: POSTGRES
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_PORT_5432_TCP_ADDR: postgres
          POSTGRES_DATABASE: keycloak
          JDBC_PARAMS: 'connectTimeout=30'
        ports:
        - '18080:8080'
        - '18443:8443'
        volumes:
        - data-keycloak:/data
        networks:
        - osdr-net-ext
        depends_on:
        - postgres

volumes:
    data-keycloak:
    data-pstgresql:

networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
